# Generated by Django 2.2.13 on 2021-03-31 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210330_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Profile'),
        ),
    ]
